#ifndef __PROJECT_CONF_H__
#define __PROJECT_CONF_H__

#define MM_CONF_MAJORITY MM_MAJORITY_H0

#define LC_CONF_TYPE LC_TYPE_SHIFT	

#define LS_CONF_MAX_LOOP_COUNT				20

#define LS_CONF_MAX_NONIMPROVED_CONTINUOUS_LOOP_COUNT   8

#endif
